on:
  push:
    branches:
      - main

name: Production deployment

jobs:
  live-job:
    environment: Live
    runs-on: ubuntu-latest
    if: ${{ github.environment }} == 'Live'
    steps:
      - run: echo "${{ vars.ENV_VAL }}"  >> $GITHUB_STEP_SUMMARY
